eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: userinfo
  rabbitmq:
    host: localhost
    port: 5672
    username: wsw92
    password: 123123  
