eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8791
spring:
  application:
    name: web-feign
  rabbitmq:
    host: localhost
    port: 5672
    username: wsw92
    password: 123123  
feign:
  hystrix: 
    enabled: true