eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: wsw92
    password: 123123  
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: web
    api-b:
      path: /api-b/**
      serviceId:  web-feign
foo: fooshhahdsfasdf